# Generated by Django 6.0.1 on 2026-02-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_purchase_created_at_sale_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='gst_rate',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='is_interstate',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sgst',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='taxable_value',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='sale',
            name='gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
